apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collectl
  namespace: collectl
  labels:
    app: collectl
spec:
  selector:
    matchLabels:
      app: collectl
  template:
    metadata:
      labels:
        app: collectl
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        collectl: "true"
      containers:
      - name: collectl
        image: quay.io/gmeghnag/collectl:4.3.20
        imagePullPolicy: Always
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 400Mi
        volumeMounts:
        - mountPath: /dev/mem
          name: mem
        - mountPath: /sys
          name: sys
        - mountPath: /var/log
          name: logs
        securityContext:
          runAsUser: 0
          privileged: true
      volumes:
      - name: mem
        hostPath:
          path: /dev/mem
          type: CharDevice
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: logs
        hostPath:
          path: /var/log
          type: Directory
      hostPID: true
      hostNetwork: true
      hostIPC: true
